controller_manager:
    ros__parameters:
        update_rate: 100
        use_sim_time: true

        camera_controller:
            type: forward_command_controller/ForwardCommandController

camera_controller:
    ros__parameters:
        joints: ["camera_revolute_joint"]
        interface_name: position
