publisher_forward_position_controller:
    ros__parameters:
        wait_sec_between_publish: 5
        publish_topic: "/camera_controller/commands"

        goal_names: ["pos1"]
        pos1: [-0.3]
